config/routes.rb
Rails.application.routes.draw do
  
  resources :users

  resources :sessions, only: [:create, :new, :destroy] 

  root to: 'static_pages#home'

  get '/help', to: 'static_pages#help'

  get '/about', to: 'static_pages#about'

  get '/contact', to: 'static_pages#contact'

  get '/test', to: 'static_pages#test'

  get '/signup', to: 'users#new'

  get '/signin', to: 'sessions#new'

  get '/signout', to: 'sessions#destroy' #, via: :delete

=begin
  get 'static_pages/help', to: 'static_pages#help'

  get 'static_pages/about', to: 'static_pages#about'

  get 'static_pages/contact', to: 'static_pages#contact'

  get 'static_pages/test', to: 'static_pages#test'=end=end
=end

end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	before_save { |user| user.email = user.email.downcase }
	before_save :create_remember_token
	
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\.-]+\.[a-z]{2,}\z/i

	validates :name, presence: true, length: { maximum: 50}
	validates :email, uniqueness: { case_sensitive: false }, presence: true
	validates_format_of :email, :with => VALID_EMAIL_REGEX
	validates :password, length: {minimum: 6}
	validates :password_confirmation, presence: true

	private
		def create_remember_token
			self.remember_token = SecureRandom.urlsafe_base64
		end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new

	end

	def create
		user = User.find_by_email(params[:sessions][:email])
		if user && user.authenticate(params[:sessions][:password])
			sign_in user
			redirect_to user
		else
			flash.now[:error] = "Invalid email/password combination"
			render 'new'
		end
	end

	def destroy
		sign_out
		redirect_to root_path
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

  def test
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
      sign_in @user
      flash[:success] = "Welcome to Sample App"
  		redirect_to user_path(@user)
  	else
  		render 'new'
  	end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns full title
	def full_title(page_title)
		base_title = 'Sample App'
		if page_title.empty?
			base_title
		else 
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def sign_in(user)
		cookies.permanent[:remember_token] = user.remember_token
		self.current_user = user
	end

	def signed_in?
		!current_user.nil?
	end

	def current_user=(user) # setter
		@current_user = user
	end

	def current_user # getter
		@current_user = @current_user || User.find_by_remember_token(cookies[:remember_token])
	end

	def sign_out
		self.current_user = nil
		cookies.delete(:remember_token)
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer navbar-fixed-bottom">
	<small>
		<p>Pontus Akervall</p>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
		</ul>	
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top">
	<nav class="navbar navbar-inverse">
	    <div class="container-fluid">
	        <div class="navbar-header">
	            
	            <a class="navbar-brand" id="tictactoe-logo">Sample App</a>
	        </div>
	        <div class="collapse navbar-collapse" id="myNavbar">
	            <ul class="nav navbar-nav navbar-right">
	                <li><%= link_to "Home", root_path %></li>
	                <li><%= link_to "Help", help_path %></li>
	                <% if signed_in? %>
	                	<li class="dropdown">
              			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
              			<ul class="dropdown-menu">
                			<li><%= link_to "Profile", user_path(@current_user) %></li>
                			<li><%= link_to "Settings", "#" %></li>
                			<li><%= link_to "Sign out", signout_path %></li>
              			</ul>
            			</li>
	                <% else %>
	                	<li><%= link_to "Sign in", signin_path %></li>
	                <% end %>
	                <li><%= link_to "Test", test_path %></li>
	            </ul>
	        </div>
	    </div>
	</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title><%= full_title(yield(:title)) %></title>
		<%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track' => true) %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |key, value| %>
				<%= content_tag(:div, value, class: "alert alert-#{key}")%>
			<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
			<%= debug(params) if Rails.env.development? %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
	<div class="row">
		<div class="panel panel-danger">
		<div class="panel-heading">The form contains <%= pluralize(@user.errors.count, "error")%></div>
			<div class="panel-body">
				<ul class="list-group">
					<% @user.errors.full_messages.each do |msg| %>
						<li class="list-group-item">- <%= msg %></li>
					<% end %>
				</ul>
			</div>
		</div>
	</div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>

<h1>About Us</h1>
<p>This is a slow tutorial</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>

<h1>Contact</h1>
<p>83758083 call me</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>
<p>asdasfdelp asdsads</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
	<% provide(:title, 'Home') %>

	<h1>Sample App</h1>
	<p>Find me in app/views/static_pages/home.html.erb</p>

	<%= link_to "Sign up now!", signup_path, class: "btn btn-primary" %>
	

</div>

<!-- just to show how to find an image -->

<%= link_to image_tag("imagine.png", alt: "Rails", style: "height: 5%; width: 5%"), 'http://rubyonrails.org' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<%= render 'shared/error_messages' %>

<div class="row">
	<div class="col-lg-4">
	</div>
	<div class="col-lg-4">
		<div class="panel panel-default">
			<div class="panel-heading">Signup form</div>
			<div class="panel-body">
			<%= form_for(@user) do |f| %>
				<%= f.label :name %>
				<%= f.text_field :name, class: "form-control", placeholder: "Name"  %>
				<p></p>
				<%= f.label :email, "Email" %>
				<%= f.text_field :email, class: "form-control", placeholder: "Email" %>
				<p></p>
				<%= f.label :password, "Password" %>
				<%= f.password_field :password, class: "form-control", placeholder: "Password"  %>
				<p></p>
				<%= f.label :password_confirmation, "Confirm password" %>
				<%= f.password_field :password_confirmation, class: "form-control", placeholder: "Password confirmation"  %>
				<p></p>
				<%= f.submit "Create account", class: "btn btn-large btn-primary"%>
				<p></p>
			<% end %>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<%= provide(:title,@user.name) %>
<h1>
	<%= gravatar_for @user %>
	<%= @user.name %></h1>
<%= @user.name %>, <%= @user.email%>